CREATE TABLE [dbo].[RepoForm] (
    [Id]                INT          IDENTITY (1, 1) NOT NULL,
    [CreatedDate]       DATETIME     NULL,
    [RepoDate]          DATETIME     NULL,
    [AccountNumber]     NCHAR (50)   NULL,
    [Investigator]      NCHAR (50)   NULL,
    [CloseType]         NCHAR (50)   NULL,
    [CustomerName]      NCHAR (50)   NULL,
    [Points]            NCHAR (50)   NULL,
    [RecoveryAgent]     NCHAR (50)   NULL,
    [Notes]             NCHAR (1024) NULL,
    [RecoveryAddress]   NCHAR (50)   NULL,
    [RecoveryCity]      NCHAR (50)   NULL,
    [RecoveryState]     NCHAR (50)   NULL,
    [RecoveryZip]       NCHAR (50)   NULL,
    [StorageAddress]    NCHAR (50)   NULL,
    [StorageCity]       NCHAR (50)   NULL,
    [StorageState]      NCHAR (50)   NULL,
    [StorageZip]        NCHAR (50)   NULL,
    [PoliceDept]        NCHAR (50)   NULL,
    [PoliceNumber]      NCHAR (50)   NULL,
    [PoliceBadgeNumber] NCHAR (50)   NULL,
    [KeysChecked]       BIT          NULL,
    [DrivableChecked]   BIT          NULL,
    [Personals]         NCHAR (50)   NULL,
    [IPRUpdaterd]       NCHAR (50)   NULL,
    [RepoProcessing]    NCHAR (50)   NULL,
    [Billing]           NCHAR (50)   NULL,
    [InitializedDate]   DATETIME     NULL,
    CONSTRAINT [PK_RepoForm] PRIMARY KEY CLUSTERED ([Id] ASC)
);

