//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MQEntities : DbContext
    {
        public MQEntities()
            : base("name=MQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<pra_accountsStoreProc_Result> pra_accountsStoreProc(string vinSearch)
        {
            var vinSearchParameter = vinSearch != null ?
                new ObjectParameter("vinSearch", vinSearch) :
                new ObjectParameter("vinSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pra_accountsStoreProc_Result>("pra_accountsStoreProc", vinSearchParameter);
        }
    }
}
