//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepoForm
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AccountNumber { get; set; }
        public string Investigator { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CloseTypeId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Points { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<int> AdminUserId { get; set; }
        public Nullable<int> AdminOtherUserId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CloseType CloseType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
